name: Build APK with Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable BuildKit
        run: echo '{"features":{"buildkit":false}}' | sudo tee /etc/docker/daemon.json

      - name: Restart Docker
        run: sudo systemctl restart docker

      - name: Build APK with Buildozer Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/user/app \
            kivy/buildozer:latest buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: bin/*.apk
